### ISSUE TITLE
组件AP2 运行不了

### ISSUE THREAD

**Issue by zhengpengzheng** [gs-wenbing/MVVMMall#2]
貌似都是应用 怎么配置

**Comment by gs-wenbing** [comment]
buildSrc/src/main/kotlin/BuildConfig目录下
isAppMode改为false，然后重新rebuild即可

**Comment by zhengpengzheng** [comment]
新手学习一下 老哥能加个联系方式吗

**Comment by gs-wenbing** [comment]
742330561

**Comment by xuexixuexijpg** [comment]
> 新手学习一下 老哥能加个联系方式吗

别学了，android太老了，得精通才行，建议直接vue react 这些大前端，flutter也还行，现在学还得学compose，不过没啥两样，都是api调用，哈哈，要我看后端才有钱途

**Comment by pengzee** [comment]
> > 新手学习一下 老哥能加个联系方式吗
> 
> 别学了，android太老了，得精通才行，建议直接vue react 这些大前端，flutter也还行，现在学还得学compose，不过没啥两样，都是api调用，哈哈，要我看后端才有钱途

作为程序员这些都得学，学Android和学Flutter并不冲突
